# vim: set syntax=python:

def build(bld):
    t = bld.program(
        name = 'tastis.e',
        source = 'tastis.c',
        target = 'tastis.e',
        use = ['calstis','tables'] + bld.env.LOCAL_LIBS,
        lib = bld.env.EXTERNAL_LIBS,
        libpath = bld.env.LIBPATH,
        install_path = '${PREFIX}/bin'
        )